Align Apache Kafka Libraries
nebula-plugins/gradle-resolution-rules pull request #68
Opened 2022-01-07 12:09 UTC by Fleshgrinder

Apache Kafka releases all libraries in tandem but does not provide a BOM or platform.

2022-02-20 13:17 UTC, Fleshgrinder commented
I guess contributions aren't welcome? Should I close this? 😕

2022-02-22 18:04 UTC, rpalcolea requested changes

2022-02-22 18:04 UTC, rpalcolea commented on src/main/resources/align-apache-kafka.json
> +            "name": "align-apache-kafka",
this one looks good 

Any chance you could add an integration test similar to https://github.com/nebula-plugins/gradle-resolution-rules/blob/main/src/integTest/groovy/nebula/plugin/resolutionrules/AlignSpringKafkaIntegrationSpec.groovy ?

2022-02-23 18:05 UTC, merged

2022-02-23 20:44 UTC, rpalcolea commented
Hi @Fleshgrinder, this is now released. Thanks again for your contribution!